{
  "formatVersion": "1.1",
  "component": {
    "group": "com.loglens",
    "module": "loglens-spring-boot-starter",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "url": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "size": 41338,
          "sha512": "3ad4162fdeab74032dee772eb4c1ae9b6649d5b0481de0c9ac473e1a7b3c30ba8917d2ea0572473f8b41f8aa4896e704678df8c8c8398bcbcc18225bf0551bc7",
          "sha256": "c291c2ba8c40adf096a41fa7c0c4cc8f8a763ab0b0f9d8082ceaa6091bf9c747",
          "sha1": "e8a6989b543a94afda48715f1c0b4d31ccb33603",
          "md5": "a3c2ce5668969b5e0fed90b699664a60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "url": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "size": 41338,
          "sha512": "3ad4162fdeab74032dee772eb4c1ae9b6649d5b0481de0c9ac473e1a7b3c30ba8917d2ea0572473f8b41f8aa4896e704678df8c8c8398bcbcc18225bf0551bc7",
          "sha256": "c291c2ba8c40adf096a41fa7c0c4cc8f8a763ab0b0f9d8082ceaa6091bf9c747",
          "sha1": "e8a6989b543a94afda48715f1c0b4d31ccb33603",
          "md5": "a3c2ce5668969b5e0fed90b699664a60"
        }
      ]
    }
  ]
}
