{
  "formatVersion": "1.1",
  "component": {
    "group": "com.loglens",
    "module": "loglens-spring-boot-starter",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "url": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "size": 46678,
          "sha512": "c2f2ce6dd188e487fcab3ddf356cb81c3184a864db5acde52973f6ff0bce27435ede38a0191c241b8be875be8cb0a140b0e5efc4b224377fc37900ff59d7a51c",
          "sha256": "30d8f3896f2d66eaa8371dc4887e043021f7af5240a93b529efe593511a470f6",
          "sha1": "c06c89633fd219d8cdaa931f581d67faa672e713",
          "md5": "a7184827d57f0b7a43a47c3545477dfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "url": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "size": 46678,
          "sha512": "c2f2ce6dd188e487fcab3ddf356cb81c3184a864db5acde52973f6ff0bce27435ede38a0191c241b8be875be8cb0a140b0e5efc4b224377fc37900ff59d7a51c",
          "sha256": "30d8f3896f2d66eaa8371dc4887e043021f7af5240a93b529efe593511a470f6",
          "sha1": "c06c89633fd219d8cdaa931f581d67faa672e713",
          "md5": "a7184827d57f0b7a43a47c3545477dfa"
        }
      ]
    }
  ]
}
