{
  "formatVersion": "1.1",
  "component": {
    "group": "com.loglens",
    "module": "loglens-spring-boot-starter",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "url": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "size": 41453,
          "sha512": "66cf26848fb295510a2c4cfb1d9864692bc19098685e06aad4249e732354443ed9f476bd8d8a6e50f27a5ae0c77df4c3b75659256af1696264751f411af24586",
          "sha256": "307fbea9fe92afaee75183548795573e902b4a8e93aaf2c2cc53bc696042d8d9",
          "sha1": "d6bf6a4c4253e1333037efa1a47ec6df58d9fbc2",
          "md5": "e8da4083dfc1a0d006a2f5f99cbdb4d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.5.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "url": "loglens-spring-boot-starter-1.1.0-plain.jar",
          "size": 41453,
          "sha512": "66cf26848fb295510a2c4cfb1d9864692bc19098685e06aad4249e732354443ed9f476bd8d8a6e50f27a5ae0c77df4c3b75659256af1696264751f411af24586",
          "sha256": "307fbea9fe92afaee75183548795573e902b4a8e93aaf2c2cc53bc696042d8d9",
          "sha1": "d6bf6a4c4253e1333037efa1a47ec6df58d9fbc2",
          "md5": "e8da4083dfc1a0d006a2f5f99cbdb4d9"
        }
      ]
    }
  ]
}
